# Generated by Django 3.2.23 on 2025-03-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tarea', models.CharField(max_length=200)),
                ('descripcion_tarea', models.TextField()),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField()),
                ('estado_tarea', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='empleados.empleado')),
            ],
            options={
                'db_table': 'tareas',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
